import './globals.css'
import type { Metadata } from 'next'
import { Play } from 'next/font/google'
import { MobileNav } from '../components/sections/MobileNav'
import { Nav } from '~/components/sections/Nav'
import { ThemeController } from '~/components/controller/ThemeController'

const inter = Play({ subsets: ['latin'], weight: '700' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const appContainerStyle = {

    backgroundColor: 'white',
    maxWidth: '80vw',
    borderRadius: '10px',
    width: '100%',
    margin: '0 auto',
    height: '100%',
    padding: '10px',
    boxShadow: '0px 0px 10px rgba(0, 0, 0, 0.1)'

  }

  return (
    <html lang="en" >
      <body className={inter.className} >
        <div
          className='px-2.5 md:px-20 min-h-screen w-full bg-gradient-to-r from-slate-200
       to-slate-300 dark:bg-gradient-to-l dark:from-slate-800 
        dark:to-slate-900 flex flex-col items-center justify-start' >
          <ThemeController >
            <MobileNav />
            <Nav />
            {children}
          </ThemeController>
        </div>
      </body>
    </html>
  )
}
