import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { MobileNav } from './MobileNav'
import { ThemeController } from '~/controller/ThemeController'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeController >
          <MobileNav />
          {children}
        </ThemeController>
      </body>
    </html>
  )
}
